; document.write(
    heading(underline('From CPT112 User-Centred Design Discussion Board'), 4)
    + bold('Forum: ') + 'Assignment 1'
    + br + bold('Thread: ') + 'UI'
    + br
    + br + underline('Shyam, 2016-06-10 13:58:36 AEST')
    + br + '<div><div><p><span style="color: rgb(0,51,102);font-family: courier new , courier;">Hello William,</span></p> <p><span style="color: rgb(0,51,102);font-family: courier new , courier;">Can we </span><span style="color: rgb(0,51,102);font-family: courier new , courier;">choose an software system without a GUI?</span></p> <p><span style="color: rgb(0,51,102);font-family: courier new , courier;">I want to do a <a class="WTF" title="https://xkcd.com/378/" href="https://xkcd.com/378/" rel="nofollow">console application</a> with a UX that more than makes up for the lack of any GUI. Although there is a GUI front-end, I\'d rather not mention it; the only occurrence&nbsp;I currently have is a question in the survey asking if the user actually uses it. I cannot imagine an existing user-base for the GUI front-end; but it may be for non UNIX-based users, which I think will be an entertaining statistic...</span></p></div></div>'
    + underline('William, 2016-06-10 15:43:41 AEST')
    + br + '<div class="default"> <div><p>Hi Shyam,</p> <p>Usually the main reason why we would want to conduct such a survey is to improve the system. I would discourage studying a non-GUI product as it is highly unlikely it will be worked on and also there is almost no UX work on CLI based products. One reason is that most CLI users have no alternatives but to learn all the intricacies involved in operating such a system, either from their own volition or because they were instructed by their boss or clients.&nbsp;</p> <p>I noticed you have emailed me regarding this as well, just thought other students may benefit if I reply here. <br></p></div></div>'
    + underline('Shyam, 2016-06-10 16:43:55 AEST')
    + br + "<div> <div><p><span style='font-family: courier new , courier;color: rgb(0,51,102);'>Hello William,</span></p> <p><span style='font-family: courier new , courier;color: rgb(0,51,102);'><span style='text-decoration: underline;'><strong>V</strong></span>i is a CLI based product that was <span style='text-decoration: underline;'><strong>IM</strong></span>proved upon, which is how <span style='text-decoration: underline;'><strong>VIM</strong></span> got it's name.</span></p> <p><span style='font-family: courier new , courier;color: rgb(0,51,102);'>All software has a learning curve to some degree; just some steeper than others. Vim has a unique UX once it's learned; and VimTutor also has a unique UX for learning to use Vim, even though it is simply an ¿interactive? document.</span></p> <p><span style='font-family: courier new , courier;color: rgb(0,51,102);'>No software system is perfect; otherwise <em>everyone</em> would be using it. There are competitors against Vim; Emacs, Sublime, and whatever the future brings...</span></p> <p><span style='font-family: courier new , courier;color: rgb(0,51,102);'>&lt;edit&gt;<br>I think programming languages could/should also be considered for the assignment.<br>There are visual programming languages, but even the non-visual ones have UX; consider Python which adopts a pseudo-code style, and compare it against a C style language like Perl.<br>&lt;/edit&gt;</span></p></div></div>"
    + underline('Shyam, 2016-06-10 17:49:15 AEST')
    + br + '<div><div><p><span style="font-family: courier new , courier;color: rgb(0,51,102);">UX is not confined to GUI applications.</span></p> <p><span style="font-family: courier new , courier;color: rgb(0,51,102);">Apple invented the mouse, which introduced an entirely unique UX compared against the keyboard; which is what GUI applications depend on.</span><br> <span style="font-family: courier new , courier;color: rgb(0,51,102);">Touch screen technology is just an improvement on mouse technology; even on "smart" devices, they still have (virtual) keyboards!</span><br> <span style="font-family: courier new , courier;color: rgb(0,51,102);">Voice recognition is a developing technology designed to replace/improve on the keyboard.</span></p> <p><span style="font-family: courier new , courier;color: rgb(0,51,102);">Even the keyboard itself has design capabilities.</span><br> <span style="font-family: courier new , courier;color: rgb(0,51,102);">There are braille keyboards for the blind in the style of traditional keyboards, and also some other weird type of "keyboard"; if you can even call it that...</span><br> <span style="font-family: courier new , courier;color: rgb(0,51,102);">And there is the innovative <a class="WTF" title="https://ultimatehackingkeyboard.com/" href="https://ultimatehackingkeyboard.com/" rel="nofollow">Ultimate Hacking Keyboard</a>.</span></p> <p><span style="font-family: courier new , courier;color: rgb(0,51,102);">And then there\'s Master Foo, who enlightens us all on the <a class="WTF" target="_blank" title="http://catb.org/esr/writings/unix-koans/gui-programmer.html" href="http://catb.org/esr/writings/unix-koans/gui-programmer.html" rel="nofollow">pitfalls of GUI</a>.</span></p> <p><strong><span style="font-family: courier new , courier;color: rgb(0,51,102);">Devs are users. Devs are human. Devs do not practice the dark <span class="WTF" style="text-decoration: underline;">arts</span>. Devs do not design. Design for devs!</span></strong></p> <p><span style="font-family: courier new , courier;color: rgb(128,128,128);">...or is Dev-Centered Design a different course altogether?</span></p> <div style="left: -10000.0px;top: 0.0px;width: 1.0px;height: 1.0px;overflow: hidden;"><span style="font-family: courier new , courier;color: rgb(0,51,102);">Devs are users. Devs are human. Devs do not practice the dark arts. Devs do not design. Design for devs!</span></div></div></div>'
    + underline('Shyam, 2016-06-10 18:04:51 AEST')
    + br + '<div><div><p><span style="color: rgb(0,51,102);font-family: courier new , courier;">Keyboard-driven design is the best design; because everything is accessible through the finger tips, instead of having to navigate through someone elses maze.</span></p> <p><span style="color: rgb(0,51,102);font-family: courier new , courier;">&lt;edit&gt;I whisper sweet nothings to my machine and it just listens to me (like nobody else will); I am a Computer Whisperer, but I whisper with my finger tips...&lt;/edit&gt;</span></p></div></div>'
    + underline('Shyam, 2016-06-10 20:00:35 AEST')
    + br + '<div><div><p><span style="font-family: courier new , courier;color: rgb(0,51,102);"><a class="WTF" target="_blank" title="http://www.dvorak-keyboard.com/" href="http://www.dvorak-keyboard.com/" rel="nofollow">Dvorak</a> is a redesign of the QWERTY keyboard configuration...</span></p> <p><span style="font-family: courier new , courier;color: rgb(0,51,102);">&lt;edit&gt;<a class="WTF" target="_blank" title="http://www.workmanlayout.com/" href="http://www.workmanlayout.com/" rel="nofollow">Workman</a> is a new one I\'ve been planning to try for a while now...&lt;/edit&gt;</span></p></div></div>'
    + underline('Shyam, 2016-06-10 20:13:52 AEST')
    + br + '<div><div><p><span style="font-family: courier new , courier;color: rgb(0,51,102);"><a class="WTF" target="_blank" href="http://www.smithsonianmag.com/arts-culture/fact-of-fiction-the-legend-of-the-qwerty-keyboard-49863249/?no-ist" rel="nofollow">QWERTY</a> is comparable&nbsp;to <a class="WTF" target="_blank" title="http://gizmodo.com/why-we-still-use-qwerty-keyboards-even-though-theyre-a-1643855077" href="http://gizmodo.com/why-we-still-use-qwerty-keyboards-even-though-theyre-a-1643855077" rel="nofollow">Comic Sans MS</a></span><span style="font-family: courier new , courier;color: rgb(0,51,102);">.</span></p></div></div>'
    + '...'
)


